mod 'puppet-nodejs', '2.3.0'
mod 'puppetlabs-ntp', '6.0.0'
mod 'puppetlabs-stdlib', '4.16.0'
mod 'maestrodev-wget', '1.7.3'

mod "ghost",
  :git => "https://github.com/rivethead42/puppet-ghost.git",
  :ref => "master"

mod "profile",
  :git => "https://github.com/rivethead42/puppet-profile.git",
  :ref => "master"

mod "role",
  :git => "https://github.com/rivethead42/puppet-role.git",
  :ref => "master"
